Updating BuildRequires and Requires
Add python-crypto as a BuildRequires
downstream brew build was failing building sample config files
trying to import Crypto

File "/builddir/build/BUILD/heat-6.0.1.dev345/heat/common/crypt.py", line 17, in <module>
    from Crypto.Cipher import AES
    ImportError: No module named Crypto.Cipher

Also updating Requires based on rdopkg reqcheck

Dropped the following as they are not yet in OSP
-Requires: python-magnumclient >= 2.0.0
-Requires: python-monascaclient >= 1.0.30
-Requires: python-senlinclient >= 0.3.0

Change-Id: I127c537420d925f75d851951f421498391656b7f